language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

matrix:
    include:
        - php: 5.6
          env: deps=low
    allow_failures:
        - php: hhvm

env:
    global:
        - deps=no

before_install:
    - composer self-update

install:
    - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;
    - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; fi

script:
    - vendor/bin/phpunit -v

notifications:
  email: "douglas@usemarkup.com"

sudo: false
dist: trusty
